# Generated by Django 3.0.7 on 2021-04-27 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('small', '0004_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='small.Customer'),
        ),
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.IntegerField(default=20, null=True),
        ),
    ]
